### ISSUE TITLE
Fatal Error Call to undefined function mb_convert_encoding()

### ISSUE THREAD

**Issue by ipajen** [OllieJones/index-wp-mysql-for-speeed#66]
### Environment
- WordPress: 6.3-RC3
- PHP: 8.3.0beta2
- Server: Apache/2.4.54 (Win64) PHP/8.3.0beta2 mod_fcgid/2.3.10-dev
- Database: mysqli (Server: 8.0.31 / Client: mysqlnd 8.3.0beta2)
- Browser: Edge 115.0.1901.188 (Windows 10/11)
- Latest main code from github for index-wp-mysql-for-speed
- Metadata uploaded to id QYckkWpz

When starting monitoring at /wp-admin/tools.php?page=imfs_settings&tab=monitor_database_operations

`[06-Aug-2023 17:42:21 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function mb_convert_encoding() in C:\wamp64\www\wordpress\wp-content\plugins\index-wp-mysql-for-speed-2f15cb4144129aea6b7e2ddff9e439c5a6518372\code\querymon.php:52
Stack trace:
#0 C:\wamp64\www\wordpress\wp-includes\class-wp-hook.php(310): ImfsMonitor->imfsMonitorGather('')
#1 C:\wamp64\www\wordpress\wp-includes\class-wp-hook.php(334): WP_Hook->apply_filters(NULL, Array)
#2 C:\wamp64\www\wordpress\wp-includes\plugin.php(517): WP_Hook->do_action(Array)
#3 C:\wamp64\www\wordpress\wp-includes\load.php(1252): do_action('shutdown')
#4 [internal function]: shutdown_action_hook()
#5 {main}
  thrown in C:\wamp64\www\wordpress\wp-content\plugins\index-wp-mysql-for-speed-2f15cb4144129aea6b7e2ddff9e439c5a6518372\code\querymon.php on line 52`

**Comment by OllieJones** [comment]
Thanks for the defect report.

The monitoring function in this plugin requires the mbstring extension. Why? It's necessary reliably to parse queries gathered by the monitoring function. Queries may contain serialized text with unpredictable multibyte characters, and this corrects them.

w.org recommends including it in host php configurations. https://make.wordpress.org/hosting/handbook/server-environment/#php-extensions

I suppose it would be wise to disable the monitoring function if the mbstring extension is missing.
