### ISSUE TITLE
Fatal Error: Uncaught TypeError: log()

### ISSUE THREAD

**Issue by midweste** [OllieJones/index-wp-mysql-for-speeed#77]
Newest version throwing fatal on /wp-admin/tools.php?page=imfs_settings&tab=monitor_database_operations and /wp-admin/tools.php?page=imfs_settings&tab=high_performance_keys

```
[09-Apr-2024 23:18:24 UTC] PHP Fatal error:  Uncaught TypeError: log(): Argument #1 ($num) must be of type float, string given in /app/web/wp-content/plugins/index-wp-mysql-for-speed/afp/factory/_common/utility/base_utility/AdminPageFramework_Utility.php:138
Stack trace:
#0 /app/web/wp-content/plugins/index-wp-mysql-for-speed/afp/factory/_common/utility/base_utility/AdminPageFramework_Utility.php(138): log('-', 1024)
#1 /app/web/wp-content/plugins/index-wp-mysql-for-speed/afp/factory/_common/_abstract/_view/AdminPageFramework_PageLoadInfo_Base.php(48): Imfs_AdminPageFramework_Utility_String::getReadableBytes('-')
#2 /app/web/wp-content/plugins/index-wp-mysql-for-speed/afp/factory/_common/_abstract/_view/AdminPageFramework_PageLoadInfo_Base.php(37): Imfs_AdminPageFramework_PageLoadInfo_Base->___getPageLoadStats()
#3 /app/web/wp-includes/class-wp-hook.php(324): Imfs_AdminPageFramework_PageLoadInfo_Base->_replyToGetPageLoadInfo('<span class='ap...')
#4 /app/web/wp-includes/plugin.php(205): WP_Hook->apply_filters('<span class='ap...', Array)
#5 /app/web/wp-admin/admin-footer.php(65): apply_filters('update_footer', '')
#6 /app/web/wp-admin/admin.php(297): require_once('/app/web/wp-adm...')
#7 /app/web/wp-admin/tools.php(40): require_once('/app/web/wp-adm...')
#8 {main}
  thrown in /app/web/wp-content/plugins/index-wp-mysql-for-speed/afp/factory/_common/utility/base_utility/AdminPageFramework_Utility.php on line 138
```

**Comment by OllieJones** [comment]
Thanks for the bug report and sorry for the inconvenience. Fixed in next release. This can be concealed by removing WP_DEBUG.
